In [31]:
x=int(input())
y=int(input())
z=chr(input())


def cal(a,b,c):
    if(c=='+'):
        print(a+b)
    if(c=='-'):
        print(a-b)
    if(c=='*'):
        print(a*b)
    if(c=='%'):
        print(a%b)
        
cal(x,y,z)        
 

 4
 5
 +


TypeError: 'str' object cannot be interpreted as an integer

In [4]:
import numpy as np

a=np.random.rand(5,4)
b=np.random.rand(5,4)
c=a+b
print(a)
print(b)
print(c)


[[0.760936   0.56866004 0.89295753 0.31877331]
 [0.77845085 0.82431318 0.27705893 0.35032016]
 [0.12673791 0.77585148 0.05539416 0.43835179]
 [0.96610938 0.98312336 0.67949035 0.85976065]
 [0.71210274 0.25846834 0.33702997 0.15237045]]
[[0.93508484 0.16028602 0.20172995 0.38331686]
 [0.91283045 0.23899362 0.16552335 0.75840765]
 [0.89575466 0.69813169 0.41148901 0.26354257]
 [0.88454175 0.45290522 0.59466399 0.48707447]
 [0.59687279 0.02358834 0.54584068 0.77091576]]
[[1.69602084 0.72894606 1.09468748 0.70209018]
 [1.69128129 1.0633068  0.44258228 1.10872781]
 [1.02249257 1.47398317 0.46688318 0.70189435]
 [1.85065113 1.43602859 1.27415435 1.34683512]
 [1.30897553 0.28205668 0.88287065 0.92328621]]


In [26]:
import numpy as np
x=np.array([[1],[2]])

print(x.shape)

(2, 1)


In [12]:
x=np.array((2,3,4,))
print(x)

[2 3 4]


In [13]:
x.shape

(3,)

In [14]:
import numpy as np

a=np.random.rand(2,3,4)
b=np.random.rand(2,3,4)
c=a+b
print(a)
print(b)
print(c)


[[[0.25627068 0.2543778  0.03576148 0.30386634]
  [0.84893507 0.04445742 0.08854726 0.89728211]
  [0.32309575 0.81058624 0.89382881 0.1068559 ]]

 [[0.25625365 0.18239546 0.24085667 0.88911546]
  [0.22862339 0.2299239  0.84187776 0.10700497]
  [0.52349951 0.14390316 0.6415883  0.91718078]]]
[[[0.77892274 0.36472006 0.27018563 0.89116281]
  [0.08771606 0.07329568 0.41891687 0.57337454]
  [0.04230166 0.05544365 0.58425074 0.59907411]]

 [[0.859879   0.03779078 0.028472   0.60236463]
  [0.74211778 0.86471111 0.05106917 0.48164044]
  [0.29118992 0.68678887 0.90194718 0.07290841]]]
[[[1.03519342 0.61909786 0.30594711 1.19502915]
  [0.93665113 0.11775309 0.50746413 1.47065666]
  [0.36539741 0.86602988 1.47807954 0.70593001]]

 [[1.11613265 0.22018624 0.26932867 1.49148009]
  [0.97074117 1.094635   0.89294693 0.58864541]
  [0.81468943 0.83069203 1.54353548 0.99008919]]]


In [16]:
np.add(a,b)

array([[[1.03519342, 0.61909786, 0.30594711, 1.19502915],
        [0.93665113, 0.11775309, 0.50746413, 1.47065666],
        [0.36539741, 0.86602988, 1.47807954, 0.70593001]],

       [[1.11613265, 0.22018624, 0.26932867, 1.49148009],
        [0.97074117, 1.094635  , 0.89294693, 0.58864541],
        [0.81468943, 0.83069203, 1.54353548, 0.99008919]]])

In [17]:
s=a*5
print(a)
print(s)

[[[0.25627068 0.2543778  0.03576148 0.30386634]
  [0.84893507 0.04445742 0.08854726 0.89728211]
  [0.32309575 0.81058624 0.89382881 0.1068559 ]]

 [[0.25625365 0.18239546 0.24085667 0.88911546]
  [0.22862339 0.2299239  0.84187776 0.10700497]
  [0.52349951 0.14390316 0.6415883  0.91718078]]]
[[[1.2813534  1.271889   0.17880742 1.51933172]
  [4.24467537 0.22228708 0.4427363  4.48641056]
  [1.61547877 4.05293118 4.46914404 0.5342795 ]]

 [[1.28126823 0.91197731 1.20428334 4.44557729]
  [1.14311697 1.14961948 4.20938878 0.53502483]
  [2.61749755 0.7195158  3.20794151 4.58590391]]]


In [21]:
# a=int(input())
# b=int(input())
# h=int(input())
# x=np.random.rand(a,b,h)
# y=np.random.rand(a,b,h)





 4
 5
 6


In [28]:
import numpy as np
a,b=2,3
x,y=np.random.rand(2,3),np.random.rand(2,3)
print(a*x+b*y)

[[3.01999903 0.96463877 2.50180145]
 [3.45816839 1.39549978 0.42182633]]


In [34]:
import numpy as np
a,b=2,3
x,y=np.random.rand(2,3),np.random.rand(2,3)
x.T@y

array([[0.19054367, 0.44576641, 0.44537387],
       [0.13258749, 0.09014283, 0.08486279],
       [0.47044425, 0.59684156, 0.58441004]])

In [36]:
##Norms Concept
Refer: https://builtin.com/data-science/vector-norms

In [42]:
# Euclidian Norm
x=np.array([[3],[-4]])
np.linalg.norm(x,2) 

5.0

In [43]:
#Manhattan Norm
np.linalg.norm(x,1)

7.0

In [45]:
# Max Norm
np.linalg.norm(x,np.inf)

4.0

In [46]:
x,y=np.array([[3],[-4]]),np.array([[3],[2]])
np.linalg.norm(x-2,2)

6.0827625302982185

In [48]:
#Vector angle
x,y=np.array([[1],[2]]),np.array([[5],[-4]])
cos_theta=(x.T@y)/((np.linalg.norm(x,2))*(np.linalg.norm(y,2)))
print(cos_theta)

[[-0.20952909]]


In [50]:
cos_inverse=np.arccos(cos_theta)
print(cos_inverse)

[[1.78188966]]


In [51]:
degree=cos_inverse*((180)/np.pi)

In [52]:
print(degree)

[[102.09475708]]


In [55]:
x,y=np.array([[1],[2]]),np.array([[-1],[-2]])
cos_theta=(x.T@y)/((np.linalg.norm(x,2))*(np.linalg.norm(y,2)))
print(cos_theta)
cos_inverse=np.arccos(cos_theta)
print(cos_inverse)
degree=cos_inverse*((180)/np.pi)
print(degree)

[[-1.]]
[[3.14159263]]
[[179.99999879]]


In [58]:
x,y=np.array([[1],[2]]),np.array([[1],[-2]])
cos_theta=(x.T@y)/((np.linalg.norm(x,2))*(np.linalg.norm(y,2)))
print(cos_theta)
cos_inverse=np.arccos(cos_theta)
print(cos_inverse)
degree=cos_inverse*((180)/np.pi)
print(degree)

[[-0.6]]
[[2.21429744]]
[[126.86989765]]
