In [4]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=A=np.array([[0,2],[1,4]])
A

array([[0, 2],
       [1, 4]])

In [2]:
A*B

array([[ 0,  4],
       [ 1, 16]])

In [5]:
np.multiply(A,B)

array([[ 0,  4],
       [ 1, 16]])

In [9]:
A=np.array([[1,3,5],[2,2,-1],[1,3,2]])
A_inverse=np.linalg.inv(A)
A_inverse

array([[ 0.58333333,  0.75      , -1.08333333],
       [-0.41666667, -0.25      ,  0.91666667],
       [ 0.33333333, -0.        , -0.33333333]])

In [15]:
print(np.round(np.dot(A,A_inverse)))

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]


In [6]:

#GUSSIAN ELEMINATION METHOD
#addition or subtraction of two eq. of rows
#multiplication of an eq. by a no.
#switching eq.

In [17]:
M=np.array([[1,3,5],[2,2,-1],[1,3,2]])
Y=np.array([[-1],[1],[2]])

In [19]:
S=np.linalg.solve(M,Y)
S

array([[-2.],
       [ 2.],
       [-1.]])

In [ ]:
#A set of n linearly independent column vectors with n elements froms a basis