In [1]:
import pandas as pd
from io import StringIO
csv_data='''A,B,C,D
1.0 ,2.0, 3.0, 4.0
5.0,6.0, 7.0, 8.0
10.0, 11.0,12.0
32.0,,12.0
43.0,,2.0'''
df=pd.read_csv(StringIO(csv_data))

In [2]:
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.0  8.0
2  10.0  11.0  12.0  NaN
3  32.0   NaN  12.0  NaN
4  43.0   NaN   2.0  NaN

In [3]:
df.isnull().sum()

A    0
B    2
C    0
D    3
dtype: int64

In [4]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [10., 11., 12., nan],
       [32., nan, 12., nan],
       [43., nan,  2., nan]])

In [5]:
df.dropna(axis=0)

A    B    C    D
0  1.0  2.0  3.0  4.0
1  5.0  6.0  7.0  8.0

In [6]:
df.dropna(axis=1)

A     C
0   1.0   3.0
1   5.0   7.0
2  10.0  12.0
3  32.0  12.0
4  43.0   2.0

In [12]:
from sklearn.impute import SimpleImputer
import numpy as np
imr=SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imr=imr.fit(df.values)
imputed_data=imr.transform(df.values)
imputed_data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [10., 11., 12.,  4.],
       [32.,  2., 12.,  4.],
       [43.,  2.,  2.,  4.]])

In [16]:
imr=SimpleImputer(missing_values=np.nan, strategy='mean')
imr=imr.fit(df.values)
imputed_data=imr.transform(df.values)
imputed_data

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ],
       [10.        , 11.        , 12.        ,  6.        ],
       [32.        ,  6.33333333, 12.        ,  6.        ],
       [43.        ,  6.33333333,  2.        ,  6.        ]])

In [37]:
imr=SimpleImputer(missing_values=np.nan, strategy='median')
imputed_data=imr.fit(df.values)
imputed_data=imr.transform(df.values)
imputed_data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [10., 11., 12.,  6.],
       [32.,  6., 12.,  6.],
       [43.,  6.,  2.,  6.]])

In [31]:
imr=SimpleImputer(missing_values=np.nan, strategy='median')
imputed_data=imr.fit(df.values).transform(df.values)
# imputed_data=imr.transform(df.values)
imputed_data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [10., 11., 12.,  6.],
       [32.,  6., 12.,  6.],
       [43.,  6.,  2.,  6.]])

In [35]:
df.fillna(df.mode())

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.0  8.0
2  10.0  11.0  12.0  NaN
3  32.0   NaN  12.0  NaN
4  43.0   NaN   2.0  NaN

In [38]:
df.fillna(df.max())

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.0  8.0
2  10.0  11.0  12.0  8.0
3  32.0  11.0  12.0  8.0
4  43.0  11.0   2.0  8.0

In [39]:
df.fillna(df.min())

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.0  8.0
2  10.0  11.0  12.0  4.0
3  32.0   2.0  12.0  4.0
4  43.0   2.0   2.0  4.0

In [41]:
df.fillna(df.melt())

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.0  8.0
2  10.0  11.0  12.0  NaN
3  32.0   NaN  12.0  NaN
4  43.0   NaN   2.0  NaN

In [43]:
#Handling the categorical data
import pandas as pd
df=pd.DataFrame([
    ['green','M',10.1,'class2'],
    ['red','L',13.5,'class1'],
    ['blue','XL',15.3,'class2']
])
df.columns=['color', 'size','price','Label']
df

color size  price   Label
0  green    M   10.1  class2
1    red    L   13.5  class1
2   blue   XL   15.3  class2

In [44]:
size_mapping ={'XL':2,'L':1,'M':0}
df['size']=df['size'].map(size_mapping)
df

color  size  price   Label
0  green     0   10.1  class2
1    red     1   13.5  class1
2   blue     2   15.3  class2

In [46]:
label_mapping ={'class2':'Nambar2','class1':'nambar1'}
df['Label']=df['Label'].map(label_mapping)
df

color  size  price    Label
0  green     0   10.1  Nambar2
1    red     1   13.5  nambar1
2   blue     2   15.3  Nambar2

In [47]:
color_mapping ={'green':'hara','red':'laal','blue':'neela'}
df['color']=df['color'].map(color_mapping)
df

color  size  price    Label
0   hara     0   10.1  Nambar2
1   laal     1   13.5  nambar1
2  neela     2   15.3  Nambar2

In [48]:
daam_mapping ={10.1:'10rupiya',13.5:'tera_rupiya',15.3:'pandra'}
df['price']=df['price'].map(daam_mapping)
df

color  size        price    Label
0   hara     0     10rupiya  Nambar2
1   laal     1  tera_rupiya  nambar1
2  neela     2       pandra  Nambar2

In [49]:
inv_size_mapping={v:k for k,v in size_mapping.items()}
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: object

In [52]:
#Label Encoding 
import numpy as np
class_mapping={label:idx for idx, label in enumerate(np.unique(df['Label']))}
class_mapping

df['Label']=df['Label'].map(class_mapping)
df

inv_class_mapping={v:k for k, v in class_mapping.items()}
df['Label']=df['Label'].map(inv_class_mapping)

In [53]:
df

color  size        price  Label
0   hara     0     10rupiya      0
1   laal     1  tera_rupiya      1
2  neela     2       pandra      0

In [56]:
data=pd.read_csv("C:\Users\itsme\OneDrive\Desktop\iris.csv")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1095136697.py, line 1)